# Application
spring.application.name=learn-springboot3

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/absensi_karyawan_javaspringboot3
spring.datasource.username=root
spring.datasource.password=

# HikariCP (Connection Pool)
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
